// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:country_app/hive/hive_adaptors.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CountryEntityAdapter());
  }
}
